# Generated by Django 5.2.5 on 2025-09-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='embeddings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='embeddings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
