# Generated by Django 5.2.5 on 2025-09-10 12:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='chat_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
