# Generated by Django 5.2.5 on 2025-09-11 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_claim_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='lost_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.lostitem'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('match_found', 'Match Found')], default='pending', max_length=20),
        ),
    ]
