# Generated by Django 5.2.5 on 2025-09-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_claim_lost_item_alter_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_items_images/'),
        ),
    ]
