# Generated by Django 5.2.5 on 2025-09-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_claim_status_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='status',
            field=models.CharField(choices=[('searching', 'Searching'), ('reunited', 'Reunited')], default='searching', max_length=20),
        ),
    ]
