# Generated by Django 5.2.5 on 2025-09-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_lostitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='creation_method',
            field=models.CharField(choices=[('manual', 'Manual Claim'), ('ai_suggestion', 'AI Suggestion')], default='manual', max_length=20),
        ),
    ]
