# Generated by Django 5.2.5 on 2025-10-23 12:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_claim_exchange_token_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='exchange_token',
            field=models.CharField(default=api.models.generate_word_token, max_length=50, unique=True),
        ),
    ]
