# Generated by Django 5.2.5 on 2025-10-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_claim_exchange_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='exchange_token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
